name: Godot Android Export

on:
  push:
    branches:
      - release

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Godot Headless Build
        uses: robpc/godot-export-action@v4.3-0
        with:
          preset: Android
          export_path: build/mygame.apk
